# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=200)),
                ('user_id', models.IntegerField(max_length=10)),
                ('vehicle_model_id', models.IntegerField()),
                ('package_id', models.IntegerField(choices=[(1, '4HRS-40KMS'), (2, '8HRS-80KMS'), (3, '6HRS-60KMS'), (4, '10HRS-100KMS'), (5, '5HRS-50KMS'), (6, '3HRS-30KMS'), (7, '12HRS-120KMS')], null=True)),
                ('travel_id', models.IntegerField(choices=[(1, 'LONG_DISTANCE'), (2, 'POINT_TO_POINT'), (3, 'HOURLY_RENTAL')], null=True)),
                ('from_area_id', models.IntegerField()),
                ('to_area_id', models.IntegerField(null=True)),
                ('from_city_id', models.IntegerField()),
                ('to_city_id', models.IntegerField(null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField(null=True)),
                ('online_booking', models.BooleanField(default=True)),
                ('mobile_booking', models.BooleanField(default=False)),
                ('booking_created', models.DateTimeField(auto_now_add=True)),
                ('from_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('car_cancelation', models.BooleanField(default=False)),
            ],
        ),
    ]
