# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
