# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201101_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_id',
            field=models.IntegerField(blank=True, choices=[(1, '4HRS-40KMS'), (2, '8HRS-80KMS'), (3, '6HRS-60KMS'), (4, '10HRS-100KMS'), (5, '5HRS-50KMS'), (6, '3HRS-30KMS'), (7, '12HRS-120KMS')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_area_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_id',
            field=models.IntegerField(blank=True, choices=[(1, 'LONG_DISTANCE'), (2, 'POINT_TO_POINT'), (3, 'HOURLY_RENTAL')], null=True),
        ),
    ]
