# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201101_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_created',
            field=models.DateTimeField(),
        ),
    ]
