# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-02 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201102_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='car_cancelation',
            new_name='car_cancellation',
        ),
    ]
