# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201102_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
