# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201103_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uuid',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
