# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201103_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='to_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
