# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-04 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201103_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='uuid',
            new_name='id',
        ),
    ]
